-- 1. Criação da tabela testimonials
CREATE TABLE IF NOT EXISTS public.testimonials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    name text NOT NULL,
    role text,
    company text NOT NULL,
    text text NOT NULL,
    rating integer CHECK (rating >= 1 AND rating <= 5),
    avatar text
);

-- 2. Habilitar Row Level Security (Segurança a nível de linha) - Boa prática
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- 3. Criar políticas de acesso (Policies)
-- Permitir leitura pública (qualquer um pode ver os depoimentos)
CREATE POLICY "Permitir leitura pública" 
ON public.testimonials FOR SELECT 
USING (true);

-- Permitir inserção apenas via API (usando a Service Role, que ignora RLS, ou autenticado se for o caso)
-- Se você usar a service role no backend, não precisa de política de insert para anon, 
-- mas se quiser permitir insert público (não recomendado sem auth), teria que adicionar.
-- Como seu código usa service role no backend, o RLS não bloqueia o backend.

-- 4. Inserir os dados de exemplo (Instrumentos de Medição)
INSERT INTO testimonials (name, role, company, text, rating, avatar, created_at) VALUES
(
  'Carlos Eduardo Silva',
  'Engenheiro de Qualidade',
  'Metalúrgica TechSolutions',
  'O Fellip é um especialista. Precisávamos renovar nossos paquímetros e micrômetros para a certificação ISO. Ele indicou os modelos IP67 ideais para nosso ambiente de usinagem, com proteção contra óleo e poeira.',
  5,
  'https://xsgames.co/randomusers/assets/avatars/male/42.jpg',
  NOW() - INTERVAL '2 days'
),
(
  'Mariana Costa',
  'Gerente de Laboratório',
  'LabControl Análises',
  'Atendimento técnico impecável. A aquisição dos durômetros portáteis foi decisiva para nosso controle de qualidade em campo. O Fellip garantiu a entrega técnica e os certificados de calibração que precisávamos.',
  5,
  'https://xsgames.co/randomusers/assets/avatars/female/35.jpg',
  NOW() - INTERVAL '5 days'
),
(
  'Roberto Almeida',
  'Supervisor de Manutenção',
  'Indústria Têxtil Almeida',
  'Muito satisfeito com a compra dos termovisores. O Fellip fez uma consultoria detalhada que nos ajudou a escolher o modelo certo para nossa manutenção preditiva. Equipamento robusto e preciso.',
  4,
  'https://xsgames.co/randomusers/assets/avatars/male/12.jpg',
  NOW() - INTERVAL '1 week'
),
(
  'Fernanda Oliveira',
  'Sócia-Proprietária',
  'Usinagem Oliveira',
  'O suporte do Fellip na escolha do projetor de perfil foi excelente. Ele entendeu nossa necessidade de medição de peças complexas e conseguiu um equipamento que atende perfeitamente nossa demanda com ótimo custo-benefício.',
  5,
  'https://xsgames.co/randomusers/assets/avatars/female/68.jpg',
  NOW() - INTERVAL '2 weeks'
),
(
  'Ricardo Santos',
  'Técnico em Refrigeração',
  'ClimaFrio Serviços',
  'Comprei todo meu kit de medição (multímetro, manômetro digital e vacuômetro) com o Fellip. Honestidade na negociação e produtos de primeira linha. A precisão dos instrumentos mudou meu trabalho.',
  5,
  'https://xsgames.co/randomusers/assets/avatars/male/23.jpg',
  NOW() - INTERVAL '1 month'
);
